server:
  port: 8089

spring:
  application:
    name: Ciclo-Vida

  r2dbc:
    url: r2dbc:pool:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: postgres.rwjixaghztcpqspihqvq
    password: vallegrande2024@
